apiVersion: v1
kind: Service
metadata:
  name: bankapp-svc
  namespace: bankapp-ns
  labels:
    app: bankapp
spec:
  selector:
    app: bankapp-deploy
  ports:
  - protocol: TCP
    port: 8080          # Host/Cluster Port
    targetPort: 8080    # Container Port
