apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: bankapp-ns
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: VGVzdEAxMjM=   # base64 encoded pwd "Test@123"
  SPRING_DATASOURCE_PASSWORD: VGVzdEAxMjM= # Base64 for "Test@123"
